version: '3'
services:
  mysql:
    image: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports: 
      - '33306:3306'
    expose: 
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample
      MYSQL_USER: api-server
      MYSQL_PASSWORD: test
      TZ: "Asia/Tokyo"
    volumes:
      - ../db/conf:/etc/mysql/conf.d
      - ../db/init:/docker-entrypoint-initdb.d

  api-server:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        VARIANT: 1.16
        INSTALL_NODE: "false"
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports: 
      - '9000:9000'
    volumes:
      - ../:/app
    expose:
      - '9000'
    depends_on:
      - mysql
  
